$wallpaper = /home/xtrmn8/.config/Ax-Shell/assets/wallpapers_example/manga-berserk-moonlit-apostle.jpg
$background = 131313
$foreground = e2e2e2

$primary = ffffff
$secondary = c6c6c6
$tertiary = e2e2e2
$surface = 131313
$surface_bright = 393939
$outline = 919191
$error = 000000

$shadow = 000000

$red = ffffff
$green = ffffff
$yellow = ffffff
$blue = ffffff
$magenta = ffffff
$cyan = ffffff
$white = ffffff
$red_dim = 000000
$green_dim = 000000
$yellow_dim = 000000
$blue_dim = 000000
$magenta_dim = 000000
$cyan_dim = 000000
